# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oodle < Formula
  desc "CLI for the Oodle observability platform"
  homepage "https://github.com/oodle-ai/oodle-cli"
  version "0.15.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oodle-ai/oodle-cli/releases/download/v0.15.0/oodle-cli_0.15.0_darwin_amd64.tar.gz"
      sha256 "787fc3fd0bb94d2cf24e28dc9f14a6922ac4f5048060a0141992318878610e30"

      def install
        bin.install "oodle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oodle-ai/oodle-cli/releases/download/v0.15.0/oodle-cli_0.15.0_darwin_arm64.tar.gz"
      sha256 "897806d01b77fec1b371e54b93448397475e9770a4be5204137c967ce6810ea9"

      def install
        bin.install "oodle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oodle-ai/oodle-cli/releases/download/v0.15.0/oodle-cli_0.15.0_linux_amd64.tar.gz"
      sha256 "c8418da49c9d16b3c7ae31d6e5a4503426b53ac5801758760587b27a8b2bdc6a"
      def install
        bin.install "oodle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oodle-ai/oodle-cli/releases/download/v0.15.0/oodle-cli_0.15.0_linux_arm64.tar.gz"
      sha256 "ba67a2b4d86480cfb4c83155b5fa5f1f2887dfbf01d7ba13c441d90f4323da6f"
      def install
        bin.install "oodle"
      end
    end
  end

  test do
    system "#{bin}/oodle", "version"
  end
end
