# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oodle < Formula
  desc "CLI for the Oodle observability platform"
  homepage "https://github.com/oodle-ai/oodle-cli"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oodle-ai/oodle-cli/releases/download/v0.12.0/oodle-cli_0.12.0_darwin_amd64.tar.gz"
      sha256 "19664e57e1e8b6c9d8cccee21ef281c25ffb2c775956e210b93bbb771ac87968"

      def install
        bin.install "oodle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oodle-ai/oodle-cli/releases/download/v0.12.0/oodle-cli_0.12.0_darwin_arm64.tar.gz"
      sha256 "ddd9b2078c3158ab25ccde2e1cf2815f5f8b487b01d309bcdf3a02c13bb4dafc"

      def install
        bin.install "oodle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oodle-ai/oodle-cli/releases/download/v0.12.0/oodle-cli_0.12.0_linux_amd64.tar.gz"
      sha256 "09368116c94f5c5153155c2f6c928c99728e8458eaa7a28437f6cbb9d4062271"
      def install
        bin.install "oodle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oodle-ai/oodle-cli/releases/download/v0.12.0/oodle-cli_0.12.0_linux_arm64.tar.gz"
      sha256 "c6225d2a0afd57853d5f1a3863fa9d1b1653fc8fb592f04987174b9f66d9d865"
      def install
        bin.install "oodle"
      end
    end
  end

  test do
    system "#{bin}/oodle", "version"
  end
end
